// This file is auto-generated by scripts/generate-print-theme-manifest.mjs
// Do not edit manually.

export type PrintTheme = {
  id: string;
  label: string;
  href: string;
  className: string;
};

export const PRINT_THEMES: PrintTheme[] = [
  {
    "id": "print-dark",
    "label": "Dark",
    "href": "/themes/cv/print-dark.css",
    "className": "printTheme--dark"
  },
  {
    "id": "print-light",
    "label": "Light",
    "href": "/themes/cv/print-light.css",
    "className": "printTheme--light"
  }
] as const;

export const DEFAULT_PRINT_THEME_ID: PrintTheme['id'] =
  PRINT_THEMES.find((t) => t.id === 'print-light')?.id ?? PRINT_THEMES[0]?.id ?? 'print-light';
