export {
  normalizeSkillName,
  findSkillByName,
  ensureUniqueSkills,
  ensureUniqueSkillsCaseInsensitive,
  addSkill,
  updateSkill,
  removeSkill,
  addSkillToRole,
  removeSkillFromRole,
  updateSkillLevelOnRole,
  recalculateYears,
  linkRoleSkillsToMainSkills,
  normalizeAfterImport,
} from './competence-service';
